SELECT * FROM managers;

SELECT * FROM employees;

-- USING THE ALL OPERATOR TO FIND EMPLOYEES WHO ARE OLDER THAN ALL THE MANAGERS IN A COMPANY

SELECT * 
FROM employees
WHERE age > ALL (SELECT age FROM managers);

-- USING THE ANY OPERATOR TO FIND EMPLOYEES WHO ARE OLDER THAN ANY MANAGERS IN A COMPANY

SELECT * 
FROM employees
WHERE age > ANY (SELECT age FROM managers);
