create table inventory (
	id INT,
	product_name VARCHAR(50),
	unit_price DECIMAL(3,1),
	units_stock INT,
	units_order INT
);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (1, 'Crab - Blue, Frozen', 17.5, 4, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (2, 'Onions - Dried, Chopped', 8.1, 10, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (3, 'Dried Cranberries', 15.4, 10, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (4, 'Easy Off Oven Cleaner', 17.3, 6, 10);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (5, 'Milk - Chocolate 500ml', 6.5, 10, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (6, 'Turkey - Oven Roast Breast', 10.0, 1, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (7, 'Thyme - Lemon, Fresh', 2.6, 4, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (8, 'Lime Cordial - Roses', 18.1, 6, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (9, 'Milk - Chocolate 500ml', 1.0, 7, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (10, 'Lamb Shoulder Boneless Nz', 1.8, 2, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (11, 'Coffee - Egg Nog Capuccino', 10.3, 3, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (12, 'Durian Fruit', 4.5, 10, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (13, 'Bread - Corn Muffaletta', 6.9, 7, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (14, 'Coconut - Shredded, Unsweet', 13.2, 7, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (15, 'Cake - Night And Day Choclate', 14.0, 4, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (16, 'Tomatoes - Cherry, Yellow', 3.3, 10, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (17, 'Shrimp - Prawn', 19.0, 7, 10);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (18, 'Energy Drink - Redbull 355ml', 4.4, 10, 2);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (19, 'Cookie Dough - Chunky', 4.7, 8, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (20, 'Wine - Penfolds Koonuga Hill', 6.4, 7, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (21, 'Juice - Happy Planet', 6.6, 2, 3);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (22, 'Lamb - Leg, Bone In', 5.3, 9, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (23, 'Sponge Cake Mix - Chocolate', 1.9, 9, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (24, 'Guinea Fowl', 6.9, 8, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (25, 'Country Roll', 12.1, 10, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (26, 'Avocado', 8.0, 3, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (27, 'Pork - Loin, Bone - In', 5.2, 1, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (28, 'Octopus - Baby, Cleaned', 11.9, 1, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (29, 'Asparagus - Green, Fresh', 2.5, 7, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (30, 'Wood Chips - Regular', 8.7, 7, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (31, 'Rum - Coconut, Malibu', 16.5, 7, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (32, 'Vodka - Smirnoff', 15.0, 2, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (33, 'Nutmeg - Ground', 16.1, 2, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (34, 'Pur Value', 12.6, 5, 10);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (35, 'Cheese - Bocconcini', 15.4, 2, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (36, 'Wine - White, Pinot Grigio', 17.8, 1, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (37, 'Cheese - Brie', 14.2, 9, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (38, 'Pork - Back, Short Cut, Boneless', 3.3, 6, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (39, 'Prunes - Pitted', 6.0, 4, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (40, 'Thyme - Fresh', 2.0, 8, 3);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (41, 'Lemon Grass', 18.7, 9, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (42, 'Croissant, Raw - Mini', 18.8, 9, 3);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (43, 'Soup - Chicken And Wild Rice', 9.3, 10, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (44, 'Lobster - Baby, Boiled', 14.0, 1, 3);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (45, 'Lid Coffee Cup 8oz Blk', 9.8, 3, 10);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (46, 'Coffee Cup 12oz 5342cd', 2.6, 2, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (47, 'V8 Pet', 12.7, 1, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (48, 'Bay Leaf Ground', 19.4, 8, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (49, 'Veal - Chops, Split, Frenched', 8.8, 10, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (50, 'Bread - Crusty Italian Poly', 15.0, 5, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (51, 'Instant Coffee', 13.1, 5, 2);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (52, 'Wine - Ice Wine', 19.6, 9, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (53, 'Beef - Rib Roast, Cap On', 8.8, 2, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (54, 'Chips Potato Reg 43g', 18.2, 5, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (55, 'Bread - Raisin Walnut Pull', 14.7, 8, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (56, 'Wine - Cotes Du Rhone Parallele', 2.5, 6, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (57, 'Towel Multifold', 5.0, 7, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (58, 'Jam - Strawberry, 20 Ml Jar', 2.2, 5, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (59, 'Beans - Soya Bean', 9.8, 5, 7);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (60, 'Tea - Mint', 1.0, 5, 10);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (61, 'Smoked Paprika', 13.2, 2, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (62, 'Bread - Calabrese Baguette', 14.7, 3, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (63, 'Apple - Delicious, Golden', 19.1, 9, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (64, 'Extract - Almond', 17.7, 6, 2);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (65, 'Cornish Hen', 6.7, 7, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (66, 'Flavouring - Rum', 4.5, 6, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (67, 'Syrup - Monin, Amaretta', 9.5, 6, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (68, 'Cumin - Whole', 16.5, 1, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (69, 'Lid - 0090 Clear', 14.4, 8, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (70, 'Crush - Grape, 355 Ml', 13.6, 4, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (71, 'Sauce - Black Current, Dry Mix', 12.7, 1, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (72, 'Soy Protein', 14.6, 8, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (73, 'Wine - Spumante Bambino White', 13.3, 5, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (74, 'Beef - Roasted, Cooked', 10.4, 2, 2);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (75, 'Bread Roll Foccacia', 13.7, 1, 6);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (76, 'Pear - Halves', 3.6, 2, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (77, 'Bread Cranberry Foccacia', 17.6, 4, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (78, 'Yogurt - Banana, 175 Gr', 12.8, 7, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (79, 'Cheese - Ricotta', 18.8, 2, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (80, 'Muffin Chocolate Individual Wrap', 15.7, 5, 10);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (81, 'Parsley - Fresh', 18.5, 5, 5);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (82, 'Energy Drink - Franks Original', 12.2, 3, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (83, 'Bar Special K', 3.8, 5, 3);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (84, 'Cleaner - Pine Sol', 5.9, 4, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (85, 'Browning Caramel Glace', 3.8, 9, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (86, 'Versatainer Nc - 9388', 9.4, 9, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (87, 'Cocoa Feuilletine', 16.9, 9, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (88, 'Island Oasis - Cappucino Mix', 14.5, 5, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (89, 'Ice Cream - Life Savers', 11.5, 10, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (90, 'Beef Ground Medium', 9.3, 2, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (91, 'Cheese - Mozzarella', 15.6, 1, 1);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (92, 'Tortillas - Flour, 12', 10.8, 6, 8);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (93, 'Irish Cream - Butterscotch', 3.7, 8, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (94, 'Cake - Box Window 10x10x2.5', 5.7, 8, 4);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (95, 'Jam - Raspberry,jar', 18.8, 5, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (96, 'Clams - Bay', 11.6, 3, 9);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (97, 'Bread - Crumbs, Bulk', 15.6, 5, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (98, 'Pepsi, 355 Ml', 4.3, 8, 7);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (99, 'Cheese Cheddar Processed', 9.8, 9, null);
insert into inventory (id, product_name, unit_price, units_stock, units_order) values (100, 'Flour Dark Rye', 16.7, 5, null);
