-- This table was created on https://www.mockaroo.com
--CREATING THE SAMPLE DATA TABLE

create table SAMPLE_DATA (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20),
	age INT,
	country VARCHAR(50),
	credit_card VARCHAR(50),
	currency VARCHAR(50)
);


--INSERTING DATA INTO THE SAMPLE DATA TABLE

insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (1, 'Daron', 'Izhaky', 'dizhaky0@rambler.ru', 'Agender', '130.37.233.73', 99, 'China', 'bankcard', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (2, 'Odilia', 'Janecek', 'ojanecek1@jimdo.com', 'Female', '230.199.205.233', 18, 'Poland', 'switch', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (3, 'Colas', 'Kirsopp', 'ckirsopp2@wisc.edu', 'Male', '92.144.54.255', 37, 'Russia', 'jcb', 'RUB');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (4, 'Jedidiah', 'Itzkovwich', 'jitzkovwich3@ning.com', 'Non-binary', '34.80.6.215', 61, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (5, 'Donall', 'Cattle', 'dcattle4@spotify.com', 'Male', '182.5.117.2', 34, 'China', 'bankcard', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (6, 'Marlow', 'Martinson', 'mmartinson5@t.co', 'Male', '43.188.212.134', 25, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (7, 'Mathian', 'Chace', 'mchace6@usnews.com', 'Male', '228.222.6.251', 51, 'China', 'visa-electron', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (8, 'Laraine', 'Henken', 'lhenken7@state.tx.us', 'Female', '194.41.176.84', 68, 'Philippines', 'jcb', 'PHP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (9, 'Haywood', 'De Filippo', 'hdefilippo8@squidoo.com', 'Bigender', '93.137.106.91', 59, 'Japan', 'jcb', 'JPY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (10, 'Shara', 'Patington', 'spatington9@privacy.gov.au', 'Female', '229.52.99.246', 5, 'Portugal', 'diners-club-us-ca', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (11, 'Gwenneth', 'Tanby', 'gtanbya@independent.co.uk', 'Agender', '252.78.242.22', 30, 'Czech Republic', 'switch', 'CZK');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (12, 'Gillian', 'Mavin', 'gmavinb@xinhuanet.com', 'Female', '206.39.172.82', 33, 'Brazil', 'jcb', 'BRL');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (13, 'Blake', 'Aumerle', 'baumerlec@ftc.gov', 'Male', '5.30.42.76', 67, 'United States', 'jcb', 'USD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (14, 'Lorne', 'Saphir', 'lsaphird@google.ru', 'Female', '151.17.76.126', 21, 'Poland', 'jcb', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (15, 'Brandi', 'Heady', 'bheadye@baidu.com', 'Female', '72.233.57.111', 85, 'China', 'visa-electron', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (16, 'Von', 'Bodley', 'vbodleyf@toplist.cz', 'Male', '107.190.106.50', 56, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (17, 'Kore', 'McKeefry', 'kmckeefryg@newsvine.com', 'Female', '34.54.231.115', 46, 'Myanmar', 'laser', 'MMK');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (18, 'Inness', 'May', 'imayh@indiegogo.com', 'Male', '93.65.113.177', 30, 'Japan', 'mastercard', 'JPY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (19, 'Blondy', 'Giacomazzo', 'bgiacomazzoi@google.ca', 'Female', '117.244.171.229', 38, 'China', 'instapayment', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (20, 'Tomkin', 'Gregolotti', 'tgregolottij@umich.edu', 'Male', '167.191.63.10', 15, 'China', 'jcb', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (21, 'Freeland', 'Roark', 'froarkk@yellowbook.com', 'Male', '150.42.19.30', 47, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (22, 'Frank', 'Pawden', 'fpawdenl@ask.com', 'Male', '154.84.235.243', 36, 'China', 'maestro', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (23, 'Roberta', 'Skey', 'rskeym@hc360.com', 'Female', '151.232.200.223', 81, 'China', 'diners-club-carte-blanche', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (24, 'Aleksandr', 'Neesham', 'aneeshamn@fastcompany.com', 'Male', '15.216.65.116', 72, 'Indonesia', 'instapayment', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (25, 'Kaycee', 'Lowman', 'klowmano@google.ru', 'Female', '246.12.7.143', 59, 'China', 'jcb', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (26, 'Reagen', 'Scoterbosh', 'rscoterboshp@cnet.com', 'Male', '242.249.252.206', 62, 'Sweden', 'diners-club-us-ca', 'SEK');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (27, 'Tonie', 'Rowswell', 'trowswellq@aboutads.info', 'Female', '216.168.152.81', 92, 'Greece', 'mastercard', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (28, 'Oriana', 'Larive', 'olariver@ycombinator.com', 'Agender', '57.166.24.88', 57, 'Russia', 'americanexpress', 'RUB');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (29, 'Dale', 'Ferrai', 'dferrais@ezinearticles.com', 'Male', '4.119.194.238', 95, 'Indonesia', 'maestro', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (30, 'Amory', 'Moralis', 'amoralist@topsy.com', 'Male', '90.49.233.217', 28, 'Saint Helena', 'jcb', 'SHP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (31, 'Vale', 'Luparto', 'vlupartou@arstechnica.com', 'Female', '46.80.164.110', 99, 'Indonesia', 'diners-club-international', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (32, 'Kathlin', 'Millberg', 'kmillbergv@addthis.com', 'Female', '111.13.73.118', 59, 'Sweden', 'americanexpress', 'SEK');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (33, 'Lorie', 'Brusby', 'lbrusbyw@about.com', 'Female', '102.229.68.14', 54, 'Poland', 'diners-club-us-ca', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (34, 'Myrah', 'Guinness', 'mguinnessx@goo.ne.jp', 'Female', '45.254.176.142', 71, 'United States', 'diners-club-international', 'USD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (35, 'Annecorinne', 'Gascone', 'agasconey@boston.com', 'Female', '197.28.39.13', 64, 'Sri Lanka', 'visa', 'LKR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (36, 'Carver', 'Paulon', 'cpaulonz@bing.com', 'Male', '153.252.78.120', 76, 'United States', 'jcb', 'USD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (37, 'Wilhelmine', 'Leadbitter', 'wleadbitter10@bloglines.com', 'Female', '212.213.232.225', 10, 'Philippines', 'jcb', 'PHP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (38, 'Brittney', 'O''Loughnan', 'boloughnan11@usda.gov', 'Female', '30.40.165.117', 44, 'Indonesia', 'mastercard', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (39, 'Ellerey', 'Malpass', 'emalpass12@army.mil', 'Male', '206.73.233.96', 6, 'Guatemala', 'mastercard', 'GTQ');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (40, 'Larisa', 'Hazeley', 'lhazeley13@github.com', 'Female', '73.24.115.9', 33, 'Serbia', 'mastercard', 'RSD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (41, 'Lyn', 'Dmitrievski', 'ldmitrievski14@barnesandnoble.com', 'Female', '159.166.137.52', 96, 'Saudi Arabia', 'maestro', 'SAR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (42, 'Elita', 'Gregan', 'egregan15@reddit.com', 'Bigender', '89.83.233.131', 25, 'Palestinian Territory', 'jcb', 'ILS');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (43, 'Jackquelin', 'Tommeo', 'jtommeo16@dedecms.com', 'Female', '2.189.128.14', 5, 'Ukraine', 'visa-electron', 'UAH');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (44, 'Morgan', 'Hutchin', 'mhutchin17@51.la', 'Agender', '241.56.138.102', 85, 'Poland', 'jcb', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (45, 'Rolph', 'Heyworth', 'rheyworth18@joomla.org', 'Non-binary', '159.128.20.150', 3, 'Spain', 'diners-club-enroute', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (46, 'Eartha', 'Messam', 'emessam19@google.es', 'Female', '198.66.132.240', 65, 'Ukraine', 'maestro', 'UAH');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (47, 'Ax', 'Mawdsley', 'amawdsley1a@wordpress.com', 'Male', '168.234.92.221', 26, 'Philippines', 'diners-club-carte-blanche', 'PHP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (48, 'Aymer', 'Bridden', 'abridden1b@cargocollective.com', 'Male', '14.104.162.20', 15, 'Colombia', 'jcb', 'COP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (49, 'Lorelei', 'Dreini', 'ldreini1c@utexas.edu', 'Female', '52.93.26.121', 28, 'United States', 'mastercard', 'USD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (50, 'Aurlie', 'Quarmby', 'aquarmby1d@apache.org', 'Female', '141.80.239.85', 68, 'Cameroon', 'jcb', 'XAF');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (51, 'Vilma', 'Swatridge', 'vswatridge1e@hostgator.com', 'Female', '51.93.249.32', 63, 'China', 'visa', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (52, 'Deane', 'Shoute', 'dshoute1f@flickr.com', 'Female', '222.3.201.193', 7, 'Argentina', 'instapayment', 'ARS');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (53, 'Livy', 'Fuchs', 'lfuchs1g@people.com.cn', 'Female', '227.34.143.60', 94, 'Portugal', 'jcb', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (54, 'Elset', 'Greson', 'egreson1h@multiply.com', 'Genderfluid', '141.81.252.23', 82, 'Poland', 'jcb', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (55, 'Stormi', 'Auton', 'sauton1i@about.com', 'Female', '158.52.159.6', 89, 'Sweden', 'maestro', 'SEK');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (56, 'Angie', 'Trewhela', 'atrewhela1j@wisc.edu', 'Male', '130.19.59.212', 2, 'China', 'china-unionpay', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (57, 'Larina', 'Welling', 'lwelling1k@jugem.jp', 'Female', '235.94.69.39', 53, 'Peru', 'laser', 'PEN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (58, 'Adriano', 'Walthew', 'awalthew1l@utexas.edu', 'Male', '36.150.9.154', 62, 'Iraq', 'jcb', 'IQD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (59, 'Burgess', 'Boeck', 'bboeck1m@census.gov', 'Male', '75.155.86.253', 65, 'China', 'mastercard', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (60, 'Emmy', 'Harnor', 'eharnor1n@odnoklassniki.ru', 'Female', '195.178.15.149', 7, 'China', 'switch', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (61, 'Terra', 'Maymond', 'tmaymond1o@cnn.com', 'Bigender', '179.240.238.183', 7, 'China', 'jcb', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (62, 'Gustavus', 'Abrahamoff', 'gabrahamoff1p@so-net.ne.jp', 'Male', '44.97.105.82', 29, 'France', 'laser', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (63, 'Sigismundo', 'Ozanne', 'sozanne1q@latimes.com', 'Polygender', '247.71.68.167', 34, 'Russia', 'jcb', 'RUB');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (64, 'Mead', 'Oganesian', 'moganesian1r@diigo.com', 'Male', '58.75.124.255', 9, 'Brazil', 'americanexpress', 'BRL');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (65, 'Tildie', 'Nesbit', 'tnesbit1s@time.com', 'Female', '251.158.36.53', 4, 'Madagascar', 'diners-club-enroute', 'MGA');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (66, 'Aurelia', 'Aiskovitch', 'aaiskovitch1t@mit.edu', 'Female', '53.130.35.16', 100, 'Indonesia', 'visa', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (67, 'Juliann', 'Ragsdale', 'jragsdale1u@omniture.com', 'Female', '110.136.113.243', 33, 'Brazil', 'jcb', 'BRL');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (68, 'Orland', 'Nussgen', 'onussgen1v@delicious.com', 'Male', '146.22.219.224', 84, 'Poland', 'jcb', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (69, 'Ruby', 'Rowter', 'rrowter1w@wisc.edu', 'Male', '206.119.98.104', 29, 'China', 'visa', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (70, 'Nadya', 'Skouling', 'nskouling1x@xing.com', 'Female', '131.71.246.47', 38, 'Venezuela', 'jcb', 'VEF');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (71, 'Delcine', 'Cahn', 'dcahn1y@cnet.com', 'Female', '89.164.101.45', 72, 'United States', 'visa-electron', 'USD');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (72, 'Linette', 'Knight', 'lknight1z@walmart.com', 'Female', '129.115.125.5', 8, 'Poland', 'jcb', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (73, 'Richart', 'Dimeloe', 'rdimeloe20@archive.org', 'Male', '185.96.153.180', 81, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (74, 'Joanie', 'Balk', 'jbalk21@unesco.org', 'Polygender', '13.105.142.5', 62, 'China', 'jcb', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (75, 'Lillian', 'Graundisson', 'lgraundisson22@bbb.org', 'Female', '239.165.191.72', 30, 'Comoros', 'diners-club-carte-blanche', 'KMF');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (76, 'Shae', 'Parmiter', 'sparmiter23@about.com', 'Female', '77.149.206.218', 23, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (77, 'Lenka', 'Gudgen', 'lgudgen24@ovh.net', 'Female', '43.143.9.139', 64, 'China', 'jcb', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (78, 'Bron', 'Bayldon', 'bbayldon25@unesco.org', 'Male', '81.168.137.110', 20, 'France', 'diners-club-enroute', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (79, 'Ade', 'Emanuel', 'aemanuel26@nationalgeographic.com', 'Male', '229.123.112.191', 20, 'Finland', 'switch', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (80, 'Jonathan', 'Chudleigh', 'jchudleigh27@mac.com', 'Male', '84.111.112.19', 81, 'China', 'jcb', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (81, 'Claudia', 'Morfett', 'cmorfett28@mac.com', 'Female', '11.79.191.202', 71, 'Mongolia', 'diners-club-us-ca', 'MNT');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (82, 'Enrico', 'Giorgio', 'egiorgio29@printfriendly.com', 'Male', '83.74.249.202', 34, 'Indonesia', 'china-unionpay', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (83, 'Isaac', 'Gately', 'igately2a@people.com.cn', 'Male', '201.1.249.151', 55, 'China', 'mastercard', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (84, 'Felike', 'Redsull', 'fredsull2b@indiegogo.com', 'Male', '164.184.189.118', 57, 'Philippines', 'mastercard', 'PHP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (85, 'Waylin', 'Kobierzycki', 'wkobierzycki2c@dyndns.org', 'Male', '143.5.192.41', 50, 'Russia', 'jcb', 'RUB');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (86, 'Jorry', 'Yirrell', 'jyirrell2d@miitbeian.gov.cn', 'Female', '187.26.254.58', 96, 'China', 'diners-club-enroute', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (87, 'Elton', 'Gudeman', 'egudeman2e@networkadvertising.org', 'Male', '173.70.221.129', 67, 'Finland', 'instapayment', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (88, 'Nickie', 'Cudbertson', 'ncudbertson2f@dagondesign.com', 'Female', '113.38.182.65', 17, 'Poland', 'jcb', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (89, 'Nicol', 'Enevold', 'nenevold2g@wikispaces.com', 'Female', '123.96.221.217', 39, 'Ukraine', 'maestro', 'UAH');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (90, 'Geri', 'Folan', 'gfolan2h@dailymail.co.uk', 'Male', '14.227.70.227', 1, 'Dominican Republic', 'jcb', 'DOP');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (91, 'Mercie', 'Acory', 'macory2i@oakley.com', 'Female', '228.167.178.214', 16, 'China', 'switch', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (92, 'Byrle', 'O''Farrell', 'bofarrell2j@dropbox.com', 'Male', '102.107.120.70', 53, 'Poland', 'maestro', 'PLN');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (93, 'Brandy', 'Lythgoe', 'blythgoe2k@1688.com', 'Male', '62.28.95.170', 100, 'Estonia', 'china-unionpay', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (94, 'Vernice', 'Bow', 'vbow2l@exblog.jp', 'Female', '240.212.55.128', 84, 'Thailand', 'switch', 'THB');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (95, 'Bonnie', 'Smithson', 'bsmithson2m@blogtalkradio.com', 'Female', '242.147.48.73', 83, 'Indonesia', 'jcb', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (96, 'Eveleen', 'Durning', 'edurning2n@cloudflare.com', 'Female', '36.167.16.34', 36, 'Indonesia', 'visa-electron', 'IDR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (97, 'Kaila', 'Causnett', 'kcausnett2o@1688.com', 'Female', '53.209.117.124', 47, 'China', 'switch', 'CNY');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (98, 'Vale', 'Tebbett', 'vtebbett2p@google.pl', 'Female', '191.97.156.255', 65, 'Brazil', 'china-unionpay', 'BRL');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (99, 'Mignonne', 'Agott', 'magott2q@uol.com.br', 'Female', '240.214.154.194', 24, 'Austria', 'americanexpress', 'EUR');
insert into SAMPLE_DATA (id, first_name, last_name, email, gender, ip_address, age, country, credit_card, currency) values (100, 'Monica', 'Dodgson', 'mdodgson2r@etsy.com', 'Polygender', '164.211.167.175', 50, 'China', 'mastercard', 'CNY');
